const level_1 = new Level(
  [
    new Skeleton(),
    new Skeleton(),
    new Skeleton(),
    new Skeleton(),
    new Skeleton(),
    new Skeleton(),
    new Skeleton(),
    new Skeleton(),
    new Skeleton(),
    new Skeleton(),
    new Minotaur(),
  ],
  [new Bats(), new Bats(), new Bats(), new Bats(), new Bats(), new Bats(), new Bats(), new Bats()],
  [
    new Background("./assets/image/background/PNG/2/mirror5.png", -720),
    new Background("./assets/image/background/PNG/2/5.png", 0),
    new Background("./assets/image/background/PNG/2/2.png", 0),
    new Background("./assets/image/background/PNG/2/mirror5.png", 720),
    new Background("./assets/image/background/PNG/2/2.png", 720),
    new Background("./assets/image/background/PNG/2/5.png", 1440),
    new Background("./assets/image/background/PNG/2/2.png", 1440),
    new Background("./assets/image/background/PNG/2/mirror5.png", 2160),
    new Background("./assets/image/background/PNG/2/2.png", 2160),
    new Background("./assets/image/background/PNG/2/5.png", 2879),
    new Background("./assets/image/background/PNG/2/2.png", 2879),
  ],
  [new Gold(), new Gold(), new Gold(), new Gold(), new Gold(), new Gold()],
  [new Item(), new Item(), new Item(), new Item(), new Item(), new Item()]
);
